hb_blog:
    resource: "@HBBlogBundle/Controller/"
    type:     annotation
    prefix:   /
    
_besimple_soap:
    resource: "@BeSimpleSoapBundle/Resources/config/routing/webservicecontroller.xml"
    prefix:   /ws